name: Publish the release to chart repository

on:
  push:
    tags:
    - '**'

jobs:
  sync:
    uses: ArnaudTA/actions/.github/workflows/sync.yaml@feat/add-wait
    secrets:
      GILTAB_PROJECT_NAME: "${{ vars.GILTAB_PROJECT_NAME }}"
      GITLAB_MIRROR_ID: "${{ vars.GITLAB_MIRROR_ID }}"
      GITLAB_TRIGGER_TOKEN: "${{ secrets.GITLAB_TRIGGER_TOKEN }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"
      GITLAB_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
    with:
      WAIT: true

  wait-build:
    needs: sync
    uses: ArnaudTA/actions/.github/workflows/wait-pipeline.yaml@feat/add-wait
    secrets:
      GITLAB_PROJECT_ID: "${{ vars.GITLAB_PROJECT_ID }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"
      GITLAB_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
    with:
      REF: ${{ github.ref_name }}
      GRACE_PERIOD: 30
      SHA: ${{ github.sha }}
      CHECK_INTERVAL: 15

  update-chart:
    needs: wait-build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger helm-charts update
        env:
          GH_TOKEN: ${{ secrets.HELM_UPDATER }}
        run: |
          gh workflow --repo ${{ github.repository_owner }}/autocicd-infra run update-chart.yaml -f APP_VERSION=${{ github.ref_name }} -f CHART_NAME=autocicd