name: Publish the release to chart repository

on:
  push:
    tags:
    - '**'

jobs:
  sync:
    uses: ArnaudTA/actions/.github/workflows/sync.yaml@v1
    secrets:
      GILTAB_PROJECT_NAME: "${{ vars.GILTAB_PROJECT_NAME }}"
      GITLAB_MIRROR_ID: "${{ vars.GITLAB_MIRROR_ID }}"
      GITLAB_TRIGGER_TOKEN: "${{ secrets.GITLAB_TRIGGER_TOKEN }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"
      GITLAB_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
    with:
      WAIT: true

  build:
    uses: ArnaudTA/actions/.github/workflows/run-pipeline.yaml@feat/run-pipeline
    secrets:
      GITLAB_PROJECT_ID: "${{ vars.GITLAB_PROJECT_ID }}"
      GITLAB_TRIGGER_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"
      GITLAB_TOKEN: "${{ secrets.GITLAB_TOKEN }}"
      CI_VARS: |
        foo=bar
        abc=xyz
    with:
      WAIT: true
      REF: ${{ github.ref_name }}
      CI_VARS: |
        tutu=champignon

  update-chart:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger helm-charts update
        env:
          GH_TOKEN: ${{ secrets.HELM_UPDATER }}
        run: |
          gh workflow --repo ${{ github.repository_owner }}/autocicd-infra run update-chart.yaml -f APP_VERSION=${{ github.ref_name }} -f CHART_NAME=autocicd