name: Synchronize source code

on:
  push:
    branches:
    - main
    - staging
    - 'feat/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: build the app
    steps:
      - name: build docker image
        run: |
          curl -X POST --fail \
            -F token=${{ secrets.GIT_MIRROR_TOKEN }} \
            -F ref=main \
            -F variables[GIT_BRANCH_DEPLOY]=main \
            -F variables[PROJECT_NAME]=${{ vars.GILTAB_PROJECT_NAME }} \
            "${{ vars.GITLAB_URL }}/api/v4/projects/${{ vars.GITLAB_PROJECT_ID }}/trigger/pipeline"
