name: Preview on remote

on:
  push:
    branches:
      - "**"

jobs:
  sync:
    uses: ArnaudTA/actions/.github/workflows/sync.yaml@main
    secrets:
      GILTAB_PROJECT_NAME: "${{ vars.GILTAB_PROJECT_NAME }}"
      GITLAB_PROJECT_ID: "${{ vars.GITLAB_PROJECT_ID }}"
      GIT_MIRROR_TOKEN: "${{ secrets.GIT_MIRROR_TOKEN }}"
      GITLAB_URL:  "${{ secrets.GITLAB_URL }}"

  update-values:
    name: Update environment image tag
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow
        env:
          GH_TOKEN: ${{ secrets.HELM_UPDATER }}
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          LAST_PART="${BRANCH_NAME##*/}"
          echo "Last part: $LAST_PART"
          gh workflow --repo ${{ github.repository_owner }}/autocicd-values run auto-update.yaml -f ENV_NAME=$LAST_PART -f IMAGE_TAG=${{ github.sha }}